#!/bin/bash

# MovieLens https://grouplens.org/datasets/movielens/
curl -O https://files.grouplens.org/datasets/movielens/ml-latest-small.zip && unzip ml-latest-small.zip

# KMRD https://github.com/lovit/kmrd
git clone https://github.com/lovit/kmrd

# Netflix https://archive.org/details/nf_prize_dataset.tar
curl -L -O https://archive.org/download/nf_prize_dataset.tar/nf_prize_dataset.tar.gz && tar -xzvf nf_prize_dataset.tar.gz
